In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import plotly.express as px

**1. Data Collection**

In [7]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

In [8]:
print("Shape:", data.shape)
print("\nColumn Names:")
print(data.columns)
data

Shape: (9800, 18)

Column Names:
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

**2. Data Cleaning & Preprocessing**

In [9]:
print("Original Shape:", data.shape)

data = data[['Order Date', 'Region', 'Product ID', 'Sales', 'State']]

data = data.rename(columns={
    'Order Date': 'Date',
    'Product ID': 'Item',
    'State': 'Store'
})

print("New Shape:", data.shape)
data

Original Shape: (9800, 18)
New Shape: (9800, 5)

            Date   Region             Item     Sales       Store
0     08/11/2017    South  FUR-BO-10001798  261.9600    Kentucky
1     08/11/2017    South  FUR-CH-10000454  731.9400    Kentucky
2     12/06/2017     West  OFF-LA-10000240   14.6200  California
3     11/10/2016    South  FUR-TA-10000577  957.5775     Florida
4     11/10/2016    South  OFF-ST-10000760   22.3680     Florida
...          ...      ...              ...       ...         ...
9795  21/05/2017  Central  OFF-BI-10003429    3.7980    Illinois
9796  12/01/2016     East  OFF-AR-10001374   10.3680        Ohio
9797  12/01/2016     East  TEC-PH-10004977  235.1880        Ohio
9798  12/01/2016     East  TEC-PH-10000912   26.3760        Ohio
9799  12/01/2016     East  TEC-AC-10000487   10.3840        Ohio

[9800 rows x 5 columns]

In [10]:
print(data['Date'].dtype)

data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

print(data['Date'].dtype)

data

object
datetime64[ns]

           Date   Region             Item     Sales       Store
0    2017-08-11    South  FUR-BO-10001798  261.9600    Kentucky
1    2017-08-11    South  FUR-CH-10000454  731.9400    Kentucky
2    2017-12-06     West  OFF-LA-10000240   14.6200  California
3    2016-11-10    South  FUR-TA-10000577  957.5775     Florida
4    2016-11-10    South  OFF-ST-10000760   22.3680     Florida
...         ...      ...              ...       ...         ...
9795        NaT  Central  OFF-BI-10003429    3.7980    Illinois
9796 2016-12-01     East  OFF-AR-10001374   10.3680        Ohio
9797 2016-12-01     East  TEC-PH-10004977  235.1880        Ohio
9798 2016-12-01     East  TEC-PH-10000912   26.3760        Ohio
9799 2016-12-01     East  TEC-AC-10000487   10.3840        Ohio

[9800 rows x 5 columns]

In [11]:
data = data.drop_duplicates()

data = data.dropna()

data.reset_index(drop=True, inplace=True)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3958 entries, 0 to 3957
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3958 non-null   datetime64[ns]
 1   Region  3958 non-null   object
 2   Item    3958 non-null   object
 3   Sales   3958 non-null   float64
 4   Store   3958 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 154.7+ KB

In [12]:
total_sales = data['Sales'].sum()
print("Total Sales:", total_sales)

average_sales = data['Sales'].mean()
print("Average Sales:", average_sales)

max_sales = data['Sales'].max()
min_sales = data['Sales'].min()
print("Max Sales:", max_sales)
print("Min Sales:", min_sales)

Total Sales: 872358.1956
Average Sales: 220.4037886811521
Max Sales: 17499.95
Min Sales: 0.556

In [13]:
fig = px.histogram(
    data,
    x="Sales",
    nbins=40,
    title="Sales Distribution",
    marginal="box",
)

fig.show()

**4. Sales Trend Analysis**

*Analyze sales over time*

In [14]:
sales_over_time = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.line(
    sales_over_time,
    x='Date',
    y='Sales',
    title='Sales Over Time'
)

fig.update_layout(
    xaxis_title='Date',
    yaxis_title='Total Sales',
    template='plotly_white'
)

fig.show()

*Identify seasonal trends*

In [15]:
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Month_Name'] = data['Date'].dt.strftime('%b')

data

,Date,Region,Item,Sales,Store,Year,Month,Month_Name
0,2017-08-11,South,FUR-BO-10001798,261.9600,Kentucky,2017,8,Aug
1,2017-08-11,South,FUR-CH-10000454,731.9400,Kentucky,2017,8,Aug
2,2017-12-06,West,OFF-LA-10000240,14.6200,California,2017,12,Dec
3,2016-11-10,South,FUR-TA-10000577,957.5775,Florida,2016,11,Nov
4,2016-11-10,South,OFF-ST-10000760,22.3680,Florida,2016,11,Nov
...,...,...,...,...,...,...,...,...
3953,2015-05-11,South,FUR-CH-10004754,149.9000,Virginia,2015,5,May
3954,2016-12-01,East,OFF-AR-10001374,10.3680,Ohio,2016,12,Dec
3955,2016-12-01,East,TEC-PH-10004977,235.1880,Ohio,2016,12,Dec
3956,2016-12-01,East,TEC-PH-10000912,26.3760,Ohio,2016,12,Dec
3957,2016-12-01,East,TEC-AC-10000487,10.3840,Ohio,2016,12,Dec

In [16]:
monthly_sales = data.groupby(['Year','Month','Month_Name'])['Sales'].sum().reset_index()

fig = px.line(
    monthly_sales,
    x="Month_Name",
    y="Sales",
    color="Year",
    markers=True,
    title="Monthly Sales Trend (Seasonal Analysis)"
)

fig.show()

*Detect peak sales periods*

In [17]:
peak_months = monthly_sales.sort_values(by='Sales', ascending=False)

peak_months.head(10)

top_months = peak_months.head(10)

In [18]:
top_months = peak_months.head(10)

fig = px.bar(
    top_months,
    x="Month_Name",
    y="Sales",
    color="Year",
    title="Top Peak Sales Months"
)

fig.show()

**5. Store/Product Analysis**

*Compare sales across stores*

In [19]:
store_sales = data.groupby('Store')['Sales'].sum().sort_values(ascending=False).reset_index()

fig = px.bar(
    store_sales.head(10),
    x='Store',
    y='Sales',
    title='Top 10 Stores by Total Sales',
    color='Sales',
    color_continuous_scale='viridis'
)

fig.update_layout(
    xaxis_title='Store',
    yaxis_title='Total Sales',
    template='plotly_white'
)

fig.show()

*Identify best-selling products*

In [20]:
product_sales = data.groupby('Item')['Sales'].sum().sort_values(ascending=False).reset_index()

fig = px.bar(
    product_sales.head(10),
    x='Item',
    y='Sales',
    title='Top 10 Products by Total Sales',
    color='Sales',
    color_continuous_scale='magma'
)

fig.update_layout(
    xaxis_title='Product',
    yaxis_title='Total Sales',
    template='plotly_white'
)

fig.show()

*Analyze low-performing products*

In [21]:
product_sales = data.groupby('Item')['Sales'].sum().reset_index()

low_performing_products = product_sales.sort_values(by='Sales', ascending=True)

low_performing_products.head(10)

                 Item  Sales
1377  TEC-AC-10003709  0.990
362   OFF-AP-10001634  1.392
564   OFF-BI-10000201  1.476
368   OFF-AP-10002203  1.624
440   OFF-AR-10001026  2.200
1368  TEC-AC-10003433  2.376
868   OFF-LA-10002381  2.464
751   OFF-BI-10004876  2.780
176   FUR-FU-10001847  3.312
1257  OFF-SU-10001212  3.328

In [22]:
bottom_products = low_performing_products.head(10)

fig = px.bar(
    bottom_products,
    x='Item',
    y='Sales',
    title='Lowest Performing Products (Bottom 10)',
    color='Sales',
    color_continuous_scale='Reds'
)

fig.update_layout(
    xaxis_title='Product ID',
    yaxis_title='Total Sales',
    xaxis_tickangle=45
)

fig.show()

**6. Time-Based Analysis**

*Daily Sales Trends*

In [23]:
daily_sales = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.line(
    daily_sales,
    x='Date',
    y='Sales',
    title='Daily Sales Trends',
    markers=True
)
fig.show()

*Monthly Sales Trend*

In [24]:
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Month_Name'] = data['Date'].dt.strftime('%b')

monthly_sales = data.groupby(['Year','Month','Month_Name'])['Sales'].sum().reset_index()

monthly_sales = monthly_sales.sort_values(by=['Year','Month'])

fig = px.line(
    monthly_sales,
    x='Month_Name',
    y='Sales',
    color='Year',
    markers=True,
    title='Monthly Sales Trends'
)
fig.show()

*Yearly Sales Trend*

In [25]:
yearly_sales = data.groupby('Year')['Sales'].sum().reset_index()

fig = px.bar(
    yearly_sales,
    x='Year',
    y='Sales',
    text='Sales',
    title='Yearly Sales Growth Patterns',
    color='Sales',
    color_continuous_scale='Viridis'
)
fig.show()

**7. Relationship Analysis**

*Data VS Sales*

In [26]:
date_sales = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.scatter(
    date_sales,
    x='Date',
    y='Sales',
    title='Date vs Sales Relationship',
    trendline='ols'
)

fig.show()

*Store VS Sales*

In [27]:
store_sales = data.groupby('Store')['Sales'].sum().reset_index()

fig = px.bar(
    store_sales,
    x='Store',
    y='Sales',
    color='Sales',
    title='Store vs Sales Relationship',
    color_continuous_scale='Blues'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

*Product VS Sales*

In [28]:
product_sales = data.groupby('Item')['Sales'].sum().reset_index()

top_products = product_sales.sort_values(by='Sales', ascending=False).head(15)

fig = px.bar(
    top_products,
    x='Item',
    y='Sales',
    color='Sales',
    title='Product vs Sales Relationship (Top 15 Products)',
    color_continuous_scale='Viridis'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

*Identify Patterns Affecting Sales*

In [29]:
correlation = data[['Sales','Year','Month']].corr()

fig = px.imshow(
    correlation,
    text_auto=True,
    title='Correlation Between Time and Sales'
)

fig.show()

**8. Data Visualization**

*Line charts → Sales over time*

In [30]:
sales_over_time = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.line(
    sales_over_time,
    x='Date',
    y='Sales',
    title='Sales Over Time',
    markers=True
)

fig.show()

*Bar charts → Store/Product comparison*

In [31]:
store_sales = data.groupby('Store')['Sales'].sum().reset_index()

fig = px.bar(
    store_sales,
    x='Store',
    y='Sales',
    color='Sales',
    title='Store Sales Comparison',
    color_continuous_scale='Blues'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

*Histograms → Sales distribution*

In [32]:
fig = px.histogram(
    data,
    x='Sales',
    nbins=40,
    title='Sales Distribution Histogram',
    marginal='box'
)

fig.show()

*Box plots → Outlier detection*

In [33]:
fig = px.box(
    data,
    y='Sales',
    title='Sales Outlier Detection'
)

fig.show()

*Heatmaps → Correlation*

In [34]:
correlation = data[['Sales','Year','Month']].corr()

fig = px.imshow(
    correlation,
    text_auto=True,
    title='Correlation Heatmap'
)

fig.show()

**9. Business Insights**

*Identify Peak Sales Seasons*

In [38]:
monthly_sales = data.groupby(['Year','Month','Month_Name'])['Sales'].sum().reset_index()

peak_seasons = monthly_sales.sort_values(by='Sales', ascending=False)

peak_seasons.head(10)

    Year  Month Month_Name       Sales
25  2017      2        Feb  42967.9150
37  2018      2        Feb  36285.9360
36  2018      1        Jan  27367.5920
38  2018      3        Mar  26882.9530
43  2018      8        Aug  26823.6900
7   2015      8        Aug  26797.7630
24  2017      1        Jan  26342.5410
26  2017      3        Mar  25982.2870
42  2018      7        Jul  25110.4795
31  2017      8        Aug  24156.3226

In [36]:
top_peak_months = peak_seasons.head(10)

fig = px.bar(
    top_peak_months,
    x='Month_Name',
    y='Sales',
    color='Year',
    title='Peak Sales Seasons'
)

fig.show()

*Detect High-Performing Stores*

In [39]:
store_sales = data.groupby('Store')['Sales'].sum().reset_index()

top_stores = store_sales.sort_values(by='Sales', ascending=False).head(10)

top_stores

             Store        Sales
3       California  176044.3455
30        New York  123666.8900
40           Texas   81508.0546
44      Washington   52058.2540
35    Pennsylvania   36392.2290
8          Florida   33567.9305
43        Virginia   32331.6400
12         Indiana   31104.4800
31  North Carolina   28385.7330
20        Michigan   26912.3310

In [40]:
fig = px.bar(
    top_stores,
    x='Store',
    y='Sales',
    color='Sales',
    title='Top Performing Stores',
    color_continuous_scale='Viridis'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

*Understand Sales Fluctuations*

In [41]:
product_sales = data.groupby('Item')['Sales'].sum().reset_index()

top_products = product_sales.sort_values(by='Sales', ascending=False).head(10)

top_products

                 Item       Sales
1417  TEC-CO-10004722  17499.9500
1422  TEC-MA-10000822  11219.9340
1428  TEC-MA-10001127   8749.9500
609   OFF-BI-10001359   8521.4050
40    FUR-BO-10004834   8298.8316
1408  TEC-CO-10001449   8159.8640
47    FUR-CH-10000454   8148.9320
1455  TEC-MA-10004125   7999.9800
1419  TEC-MA-10000045   6965.7000
71    FUR-CH-10002024   6589.2120

In [42]:
fig = px.bar(
    top_products,
    x='Item',
    y='Sales',
    color='Sales',
    title='Top Performing Products',
    color_continuous_scale='Blues'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()